[package]
name = "TicTacToeGame"
version = "1.0.0"
authors = ["Aditya Kumar Srivastav]

[addresses]
game_address = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.15.0"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.15.0"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.15.0"
subdir = "aptos-move/framework/move-stdlib"

[dev-dependencies]